spring:
  application:
    name: example-spring-boot
logging:
  level:
    com.message.hub: debug
message:
  hub:
    dingtalk:
      bot:
        - alias: "dingtalk-bot-1"
          secret: "****"
          access-token: "*****"
